### PR TITLE
Remove tab context modifications

### PR DESCRIPTION
**Pull request by sleistner**
This PR introduces a breaking change as all modification command are removed from file tab context menu in order to better align with VSCode standards.

Closes: #120 
Closes: #121

### CODE REVIEW

**Comment by WiliTest** [comment]
Sorry but I find this reason absurd since I use VS code extensions just because I want to change the standard way VScode works. If I wanted to "align with VSCode standards", I would not have installed your extension in the first place. I don't see how having to click on the explorer or on the tab to delete a file (and customing the tab context menu) could violate the "VS standard".  

I'm probably not understanding your answer, though. What really happened? Did a VScode boss told you that it's forbidden to add too many entries on the tab context menu, if so, why, or does it create some bugs with other OS?

**Comment by sleistner** [comment]
No offence taken :)
While working on a fix I came to realise that closing or replacing a tab which is not the current active editor tab is quite cumbersome if not impossible since the current VSCode api (at least too my knowledge) does not support such behaviour. Hence I was questioning the feature and discovered that tab context menu natively does not provide any modification menu items.
There are some outstanding changes in the exposed VSCode Api, as soon as those changes are public I might get back to the problem. But for the time being I am quite reluctant to go down that quirky path.

**Comment by WiliTest** [comment]
Thank you very much for your reply, and your resilience Sleinstner!  
Ok I understand now. I would have been happy with a context menu that'd work only on active tab (the other feature you are talking about on non-active tab, is not that essential). I did not know about the "outstanding" future changes in the API, so I understand you want to wait. 
Thanks again for what you have already done for us!

**Pull request merged**
